/**
 * Copyright (C) 2015 Zalando SE (http://tech.zalando.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.zalando.stups.tokens;

/**
 * Interface definition for a provider implementation that can provide client credentials (as
 * described with the OAuth2.0 spec) which can be used to create an {@link AccessToken}.
 */
public interface ClientCredentialsProvider {

  /**
   * Get the {@link ClientCredentials} generated by this {@link ClientCredentialsProvider}
   *
   * @return    {@link ClientCredentials} that can be used to generate an {@link AccessToken}.
   * @throws CredentialsUnavailableException    Thrown in case the {@link ClientCredentialsProvider}
   * is not able to provide valid {@link ClientCredentials} at the moment. This might be the case if
   * it does not have access to valid rotated credentials e.g.
   */
  ClientCredentials get() throws CredentialsUnavailableException;
}
